# Generated by Django 4.1.13 on 2024-03-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuetionDetails',
            new_name='QuestionDetails',
        ),
    ]
