# Generated by Django 4.1.13 on 2024-03-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetails_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='certificate',
        ),
    ]
