# Generated by Django 4.1.13 on 2024-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userdetails_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='certificate',
            field=models.JSONField(default=list),
        ),
    ]
